[workspace]

members = [
    "client",
    "server"
]

[workspace.dependencies]
bevy = "0.8"

# [package]
# name = "hero-clicker"
# version = "0.1.0"
# edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

